spring.application.name=coffeeRoullet
# Expose the metrics and health endpoints
management.endpoints.web.exposure.include=health,info,metrics,prometheus

# Enable detailed metrics for your API
management.endpoint.metrics.enabled=true
management.observations.http.server.requests.enabled=true

# Add custom tags to your metrics (useful for filtering)
management.metrics.tags.application=CoffeeRoulette
